# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('offset', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=200)),
                ('days', models.CharField(choices=[('S', 'Sunday'), ('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('Y', 'Saturday')], max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HappyPlace',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=75)),
                ('neighborhood', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('cross', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happyPlaces', to='site.City')),
            ],
        ),
        migrations.AddField(
            model_name='happyhour',
            name='happyPlace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happyHours', to='site.HappyPlace'),
        ),
    ]
